---
- name: Setup macOS (Work Laptop)
  hosts: local

  vars:
    homebrew_installed_packages:
      - coreutils
      - zsh
      - starship
      - ssh-copy-id
      - git
      - pv
      - wget
      - htop
      - tmux
      - watch
      - cowsay
      - tldr
      - direnv
      - exa
      - bat
      - fzf
      - asdf
      - kubectl
      - helm

    homebrew_cask_apps:
      - iterm2
      - raycast # Use 'window management plugin'
      - rectangle
      - alt-tab
      - keka
      - shottr
      - firefox
      - google-chrome
      - discord
      - slack
      - zoom
      - iina
      - spotify
      - keepingyouawake
      - visual-studio-code
      - docker
      - font-anonymice-nerd-font
      - insomnia
      - bitwarden
      - authy
      - google-drive

    homebrew_taps:
      - homebrew/core
      - homebrew/cask-fonts
      - hashicorp/tap

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: jamesbrookes.dotfiles.zsh
    - role: jamesbrookes.dotfiles.asdf
