---
- name: Setup macOS (Work Laptop)
  hosts: local

  vars:
    homebrew_installed_packages:
      - ssh-copy-id
      - git
      - pv
      - wget
      - htop
      - tmux
      - watch
      - cowsay
      - openjdk
      - go@1.19
      - kubectl
      - helm

    homebrew_cask_apps:
      - iterm2
      - raycast
      - rectangle
      - alt-tab
      - keka
      - firefox
      - google-chrome
      - visual-studio-code
      - discord
      - slack
      - vlc
      - spotify
      - keepingyouawake
      - docker
      - font-anonymice-nerd-font
      - bitwarden
      - authy
      - shottr
      - google-drive
      - mambaforge

    homebrew_taps:
      - homebrew/core
      - homebrew/cask-fonts
      - hashicorp/tap

  roles:
    - role: geerlingguy.mac.homebrew
