---
- name: Ensure Zsh is installed
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Check if ~/.oh-my-zsh exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  ansible.builtin.git: # noqa git-latest
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    update: false
  when: not stat_oh_my_zsh_result.stat.exists

- name: Ensure configuration is present
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "u=rw,g=,o="
    block_start_string: "{!"
    block_end_string: "!}"

- name: Ensure Zsh is set as the user's logon shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
