---
- name: ZSH - Check if ~/.oh-my-zsh exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: stat_oh_my_zsh_result

- name: ZSH - Check if ~/.zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: stat_zshrc_result

- name: ZSH - Ensure oh-my-zsh exists
  ansible.builtin.git: # noqa git-latest
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    update: false
  when: not stat_oh_my_zsh_result.stat.exists

- name: ZSH - Ensure zshrc configuration is present
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "u=rw,g=,o="
    when: not stat_zshrc_result.stat.exists

# Plugins
- name: ZSH - Install zsh syntax highlighting
  ansible.builtin.git: # noqa git-latest
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
- name: ZSH - Install zsh zsh-autosuggestions
  ansible.builtin.git: # noqa git-latest
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
