---
name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install test dependencies.
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip3 install ansible

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          ansible-galaxy install -r requirements.yaml

      - name: Test the playbook's syntax.
        run: ansible-playbook macOS.yaml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook macOS.yaml
        env:
          ANSIBLE_FORCE_COLOR: '1'
