---
name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Install test dependencies.
        run: sudo pip3 install ansible

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          ansible-galaxy install -r requirements.yml

      - name: Test the playbook's syntax.
        run: ansible-playbook macOS.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook macOS.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'
