---
name: Code quality

on:
  push:

jobs:
  lint-ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ansible
        uses: ansible-community/ansible-lint-action@main
