---
name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install ansible

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          ansible-galaxy install -r requirements.yaml

      - name: Test the playbook's syntax.
        run: ansible-playbook macOS.yaml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook macOS.yaml
        env:
          ANSIBLE_FORCE_COLOR: '1'
